# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{persvr}
  s.version = "0.2.2"
  s.platform = %q{java}

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Heimbuch"]
  s.date = %q{2010-02-09}
  s.default_executable = %q{persvr}
  s.email = %q{rheimbuch@gmail.com}
  s.executables = ["persvr"]
  s.files = [
    ".gitignore",
     "Rakefile",
     "VERSION",
     "bin/persvr",
     "lib/persvr.rb",
     "lib/persvr/command.rb",
     "persvr.gemspec",
     "resource/persevere_home/WEB-INF/config/core.json",
     "resource/persevere_home/WEB-INF/lib/cometd-api-1.0.beta4.jar",
     "resource/persevere_home/WEB-INF/lib/cometd-jetty-6.1.14.jar",
     "resource/persevere_home/WEB-INF/lib/commons-cli-1.1.jar",
     "resource/persevere_home/WEB-INF/lib/commons-codec-1.3.jar",
     "resource/persevere_home/WEB-INF/lib/commons-dbcp-1.2.2.jar",
     "resource/persevere_home/WEB-INF/lib/commons-fileupload-1.2.1.jar",
     "resource/persevere_home/WEB-INF/lib/commons-httpclient-3.0.1.jar",
     "resource/persevere_home/WEB-INF/lib/commons-io-1.4.jar",
     "resource/persevere_home/WEB-INF/lib/commons-logging-1.1.jar",
     "resource/persevere_home/WEB-INF/lib/commons-pool-1.5.2.jar",
     "resource/persevere_home/WEB-INF/lib/jetty-util5-6.1.14.jar",
     "resource/persevere_home/WEB-INF/lib/jline-0.9.94.jar",
     "resource/persevere_home/WEB-INF/lib/js.jar",
     "resource/persevere_home/WEB-INF/lib/persevere.jar",
     "resource/persevere_home/WEB-INF/lib/resourceaccelerate.jar",
     "resource/persevere_home/WEB-INF/mimetypes.xml",
     "resource/persevere_home/WEB-INF/templates/ReadMe",
     "resource/persevere_home/WEB-INF/templates/index.html",
     "resource/persevere_home/WEB-INF/templates/tests.js",
     "resource/persevere_home/WEB-INF/web.xml",
     "resource/persevere_home/WEB-INF/web.xml.generic",
     "resource/persevere_home/WEB-INF/web.xml.tomcat",
     "resource/persevere_pages/index.html",
     "tasks/jeweler.rake",
     "tasks/persevere.rake",
     "tasks/persvr.thor"
  ]
  s.homepage = %q{http://github.com/rheimbuch/persvr}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Create and run instances of the Persevere JS Database.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jettr>, ["~> 0.2.1"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
    else
      s.add_dependency(%q<jettr>, ["~> 0.2.1"])
      s.add_dependency(%q<thor>, [">= 0"])
    end
  else
    s.add_dependency(%q<jettr>, ["~> 0.2.1"])
    s.add_dependency(%q<thor>, [">= 0"])
  end
end

